### ISSUE TITLE
moment getHours : _copyTime

### ISSUE THREAD

**Issue by Lars-Erik75** [h2qutc/ngx-mat-datetime-picker#11]
Hi!

After v1.0.1

fromDate.hour(), fromDate.minute(), fromDate.second() in else bracket yields errors as fromDate is not of type moment date..

_copyTime(toDate, fromDate) {
        if (toDate instanceof Date) {
            toDate.setHours(((/** @type {?} */ (fromDate))).getHours());
            toDate.setMinutes(((/** @type {?} */ (fromDate))).getMinutes());
            toDate.setSeconds(((/** @type {?} */ (fromDate))).getSeconds());
        }
        else if (moment$1.isMoment(toDate)) {
            toDate.hour(((/** @type {?} */ (fromDate))).hour());
            toDate.minute(((/** @type {?} */ (fromDate))).minute());
            toDate.second(((/** @type {?} */ (fromDate))).second());
        }
    }

**Comment by h2qutc** [comment]
Hi, this bug is fixed in version v1.0.2.
