### ISSUE TITLE
Close on click or click outside

### ISSUE THREAD

**Issue by rscherer** [h2qutc/ngx-mat-datetime-picker#13]
Hi. Great job including the timepicker. 

However, there's a way to close the popup when selecting a date or clicking outside? So the behaviour would be the same as the official datepicker.

Thanks!

**Comment by h2qutc** [comment]
Hi, I thought about this behaviour but it will be difficult for users. If popup is closed when clicking outside or selecting date, the user can choose the date without selecting time by mistaken. I think that I will add an Inout to activate this behaviour in next version. Thanks for your comment ^.^

**Comment by rscherer** [comment]
An input for this would be awesome! :) 
Thanks @h2qutc
