### ISSUE TITLE
Disable seconds

### ISSUE THREAD

**Issue by klimtron** [h2qutc/ngx-mat-datetime-picker#17]
Hello, is there any way to simple deactivate/ not show seconds on the picker and the input? Regards

**Comment by h2qutc** [comment]
Hi, the seconds can be disabled by using @Input disableSecond in version v1.0.3.

**Comment by klimtron** [comment]
Is it possible to customize the format that is displayed on input by some sort of custom attributes like [format]="yyyy:mm:dd hh:mm"? ..or any other way?

**Comment by nihilenz** [comment]
@h2qutc could you please also introduce `disableSecond` on `ngx-mat-datetime-picker`? Thanks! 🙏

**Comment by Luizgpp** [comment]
> Is it possible to customize the format that is displayed on input by some sort of custom attributes like [format]="yyyy:mm:dd hh:mm"? ..or any other way?

I want this too. You find a solution? Thanks

**Comment by Luizgpp** [comment]
I want display only 19:20 instead 19:20:44. I don't need to display seconds for the users.
