### ISSUE TITLE
To set 'stepHour' to ngx-mat-datetime-picker

### ISSUE THREAD

**Issue by jsequeira92** [h2qutc/ngx-mat-datetime-picker#25]
I want to set the 'stepHour' attribute to 3 but it is only possible to ngx-mat-timepicker component. Is there a way to set it to ngx-mat-datetime-picker?

**Comment by h2qutc** [comment]
Hi, the @Input (stepHour, stepMinute, stepSecond) are now available for datetime picker in version v1.0.3.
