### ISSUE TITLE
Make "_cancel" and "_ok" methods part of public API.

### ISSUE THREAD

**Issue by rchigvintsev** [h2qutc/ngx-mat-datetime-picker#27]
For now naming of methods `_cancel` and `_api` implies that they are not supposed to be called by clients. However I faced the situation when one of those methods turns out to be useful: manual closing of dialog and leaving date/time input value unchanged.

**Comment by h2qutc** [comment]
Hi, this bug is fixed in version v1.0.3.
The methods are renamed ok() cancel() in version v1.0.3. The picker can be now closed manually by calling cancel().
