### ISSUE TITLE
How to validate time means stop showing previous time like min date and max date?

### ISSUE THREAD

**Issue by mshubhamtyagi** [h2qutc/ngx-mat-datetime-picker#31]
In the current scenario, we can validate the date by min and max property. When I pass the min date as the current date but still, I can select the previous time. I want that if the user chooses the current date then the user could not choose the previous time.

As I attached an image you can see in this image I had the disabled date before the current date but I am unable to disable the time before the current time.

![Screenshot (36)](https://user-images.githubusercontent.com/21307943/75219029-b2e6db80-57c1-11ea-850b-4d1e7738293b.png)

**Comment by klimtron** [comment]
Could I ask how did you manage adding min/max maaking some of the dates grayed out? 
I'm trying to add [min]="minDate" [max]="maxDate" and minDate = new Date (2020, 1, 1); maxDate = new Date (2020, 4, 3); also moment.max(endDate); to the input but without any success.

**Comment by jelledrm** [comment]
@mshubhamtyagi 
How do you set the min/max date? Do you have an example?

**Comment by klimtron** [comment]
@jelledrm Try to give [min]="minDate" [max]="maxDate" for input and set minDate = moment();maxDate = moment().add(5, 'days'); using momentjs library.

**Comment by mshubhamtyagi** [comment]
@jelledrm In date picker's input field [min]="minDate" [max]="maxDate"


define in ts  
 minDate = new Date(1919, 0, 1);
 maxDate = new Date();

**Comment by taniasg** [comment]
I cannot set min or max date on my input, I defined dates on the component but still isn't working, any suggestions?

**Comment by sethigoldy** [comment]
@taniasg look at this staskblitz https://stackblitz.com/edit/demo-ngx-mat-datetime-picker?file=src%2Fapp%2Fapp.component.ts

**Comment by klimtron** [comment]
I think it's a quite high priority to have this min/max time limits.

**Comment by h2qutc** [comment]
Hi, sorry for late reply. 
The minDate/maxDate was integrated in version v2.0.2. Feel free to check it out.
When setting minDate or maxDate: 
- The calendar will disable the dates that are out of range like Angular Material Datepicker. 
- The below timepicker will not disabled, user can select the time that he want but the button Validate is only activated if the seleccted date + selected time respect the minDate/maxDate.
See [Demo here ](https://stackblitz.com/edit/demo-ngx-mat-datetime-picker)
Thank you !!!

**Comment by h2qutc** [comment]
Hi, 
This repo is no longer supported, please consider using the repository [angular-material-components](https://github.com/h2qutc/angular-material-components) instead.
This issue was fixed in [@angular-material-components/datetime-picker](@angular-material-components/datetime-picker) v2.0.1

```
npm install --save  @angular-material-components/datetime-picker
```
Free free to open issue [here](https://github.com/h2qutc/angular-material-components/issues).
Thank you very much.
