### ISSUE TITLE
moment error on install

### ISSUE THREAD

**Issue by Crocsx** [h2qutc/ngx-mat-datetime-picker#32]
I installed the package on my angular 8.2.14 project, cause it looks light a lightweight addition to `@angular/material`

I have the following error after install.

> ERROR in ./node_modules/ngx-mat-datetime-picker/fesm5/ngx-mat-datetime-picker.js
> Module not found: Error: Can't resolve 'moment' in 'C:\Users\Crocsx\Documents\github\tjx-mission\node_modules\ngx-mat-datetime-picker\fesm5'
> 

I tried to clear npm cache, redownload my modules etc..  but I need to `npm install moment` manually to make it works. 

Is it possible to make the lib work with Native Date ?

**Comment by khalilou88** [comment]
I agree with @Crocsx this lib is better without moment. Nice work by the way.

**Comment by h2qutc** [comment]
Hi, this bug is fixed in version v2.0.0.
