### ISSUE TITLE
Using ngModel binding hides seconds in date modal and hide time presentation in input

### ISSUE THREAD

**Issue by milosmih** [h2qutc/ngx-mat-datetime-picker#44]
In version 2.02 when we remove form control or use ngModel binding input immediately louse time presentation and seconds in dialog are no visible anymore.

We can see that in demo example if we remove form control from view binding.
https://stackblitz.com/edit/demo-ngx-mat-datetime-picker?file=src%2Fapp%2Fapp.component.html

**Comment by h2qutc** [comment]
Hi, 
the value of @Input disableSecond is true by default. The seconds in popup is hide by default. 
Did you test with the checkbox to disable/enable the @Input disableSecond? 
I think that  I will change the name **disableSecond** to **showSeconds** so that the user is not confused.

**Comment by milosmih** [comment]
I updated library from version 1.0.3 to 2.0.2. 
You are right, seconds are by default hidden which was not the case in previous version, sorry I did not noticed that. 

After updating to version 2.0.2 I have to import 'NgxMatNativeDateModule' also.
Is that only thing I should do ? since I have problem that I do not see time anymore at all, just date.

![NoTime](https://user-images.githubusercontent.com/16487906/76869465-a73e8000-6868-11ea-808b-0f80e079832a.PNG)

My picker looks like:
```
<mat-form-field>
  <input
    matInput
    [ngxMatDatetimePicker]="pickerStartDate"
    [ngModel]="startDate"
    (ngModelChange)="onStartDateChange($event)"
  >
  <mat-datepicker-toggle matSuffix [for]="pickerStartDate"></mat-datepicker-toggle>
  <ngx-mat-datetime-picker #pickerStartDate></ngx-mat-datetime-picker>
</mat-form-field>
```

**Comment by h2qutc** [comment]
Did you have a custom MAT_DATE_FORMATS before ? 
The NgxMatNativeDateModule use: 
const NGX_MAT_NATIVE_DATE_FORMATS: MatDateFormats = {
  parse: {
    dateInput: {
      year: 'numeric', month: 'numeric', day: 'numeric',
      hour12: false, hour: "2-digit", minute: "2-digit", second: "2-digit"
    },
  },
  display: {
    dateInput: {
      year: 'numeric', month: 'numeric', day: 'numeric',
      hour12: false, hour: "2-digit", minute: "2-digit", second: "2-digit"
    },
    monthYearLabel: { year: 'numeric', month: 'short' },
    dateA11yLabel: { year: 'numeric', month: 'long', day: 'numeric' },
    monthYearA11yLabel: { year: 'numeric', month: 'long' },
  }
};

**Comment by milosmih** [comment]
Date which is binded to picker is JavaScript date in format:

`Mon Mar 16 2020 14:40:45 GMT+0100 (Central European Standard Time)`

And that works in previous version. 

Surprisingly even when I remove binding:

```
<mat-form-field>
  <input
    matInput
    [ngxMatDatetimePicker]="pickerStartDate"
  >
  <mat-datepicker-toggle matSuffix [for]="pickerStartDate"></mat-datepicker-toggle>
  <ngx-mat-datetime-picker #pickerStartDate></ngx-mat-datetime-picker>
</mat-form-field>
```

My initial date in input control is empty. Then I open data picker pop up select some time and date and when I press ok, I get only date in input field (as I described in my previous post).

I do not know what I do wrong, what is that significant change from version 1 to version 2 which I did not update in my code.

Looks like I do not properly use component since I cannot see time.

**Comment by h2qutc** [comment]
Since the v2, the value in the input is formatted by using the property display.dateInput  of **MAT_DATE_FORMATS**. 
If you have a custom MAT_DATE_FORMATS in your project, think about modifying diplay.dateInput that I described above.
If not, can you give me an example on [https://stackblitz.com/](https://stackblitz.com/) please so that I can check ?

**Comment by dasariramacharan** [comment]
I tried replicating the issue at [link](https://stackblitz.com/edit/demo-ngx-mat-datetime-picker-yp7bar?file=src%2Fapp%2Fapp.module.ts) but was not successful yet but I do have the same issue when using Moment dates and I do not use custom format for dates

> I updated library from version 1.0.3 to 2.0.2.
> You are right, seconds are by default hidden which was not the case in previous version, sorry I did not noticed that.
> 
> After updating to version 2.0.2 I have to import 'NgxMatNativeDateModule' also.
> Is that only thing I should do ? since I have problem that I do not see time anymore at all, just date.
> 
> ![NoTime](https://user-images.githubusercontent.com/16487906/76869465-a73e8000-6868-11ea-808b-0f80e079832a.PNG)
> 
> My picker looks like:
> 
> ```
> <mat-form-field>
>   <input
>     matInput
>     [ngxMatDatetimePicker]="pickerStartDate"
>     [ngModel]="startDate"
>     (ngModelChange)="onStartDateChange($event)"
>   >
>   <mat-datepicker-toggle matSuffix [for]="pickerStartDate"></mat-datepicker-toggle>
>   <ngx-mat-datetime-picker #pickerStartDate></ngx-mat-datetime-picker>
> </mat-form-field>
> ```

**Comment by milosmih** [comment]
@dasariramacharan Thanks, I will try your solution, I am happy that I am not only one with this problem :).

@h2qutc I do not have custom format.
I tried but could not reproduce it on https://stackblitz.com/.

**Comment by h2qutc** [comment]
Hi, 
This repo is no longer supported, please consider using the repository [angular-material-components](https://github.com/h2qutc/angular-material-components) instead.
This issue was fixed in [@angular-material-components/datetime-picker](@angular-material-components/datetime-picker) v2.0.1

```
npm install --save  @angular-material-components/datetime-picker
```
Free free to open issue [here](https://github.com/h2qutc/angular-material-components/issues).
Thank you very much.
