### ISSUE TITLE
giving error in angular 9 update

### ISSUE THREAD

**Issue by vishnuramero** [h2qutc/ngx-mat-datetime-picker#47]
![error1](https://user-images.githubusercontent.com/14331629/77033514-690ea100-69cd-11ea-834c-432904143fc0.PNG)

**Comment by h2qutc** [comment]
Hi, Angular 9 is now supported, please install the version v3.x.
```
npm install --save ngx-mat-datetime-picker@3.x
```
Feel free to check it out ([demo stackblitz for Angular 9](https://stackblitz.com/edit/demo-ngx-mat-datetime-picker-angular9))
Thanks a lot !!!
