### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by EthanHipps** [h2qutc/ngx-mat-datetime-picker#49]
The time spinners and check icons are not showing after a date is selected.  Picture below of the issue.

![iconsNotShowing](https://user-images.githubusercontent.com/13156894/77105173-9706dc00-69f3-11ea-8342-10c3b5df82db.PNG)

**Comment by h2qutc** [comment]
Hi, 
Did you add the Material Design icon font to your index.html ? 
```
<link href="https://fonts.googleapis.com/icon?family=Material+Icons&display=block" rel="stylesheet">
```

**Comment by EthanHipps** [comment]
I did not. Thank you!
