### ISSUE TITLE
Cannot access 'NgxMatCalendar' before initialization

### ISSUE THREAD

**Issue by sebastianteres** [h2qutc/ngx-mat-datetime-picker#51]
I just updated to @3.0.0 after updating a project to Angular 9 and the application cannot bootstrap throwing the following error:

Cannot access 'NgxMatCalendar' before initialization

It may be something else gone wrong with my update  but just wanted to reach out in case this rings a bell to you.

Thank you!

**Comment by sebastianteres** [comment]
Downgrading to 2.0.3 fixed the issue for me

**Comment by f-aubert** [comment]
I'm having the same problem. Can't downgrade to 2.0.3 though (https://github.com/h2qutc/ngx-mat-datetime-picker/issues/46).

It also seems quite a couple peer dependencies are a bit restrictive?
 ngx-mat-datetime-picker@3.0.0" has incorrect peer dependency "@angular/platform-browser@~~9.0.7".
warning " > ngx-mat-datetime-picker@3.0.0" has incorrect peer dependency "@angular/common@~~9.0.7".
warning " > ngx-mat-datetime-picker@3.0.0" has incorrect peer dependency "@angular/core@~~9.0.7".
warning " > ngx-mat-datetime-picker@3.0.0" has incorrect peer dependency "@angular/forms@~~9.0.7".
warning " > ngx-mat-datetime-picker@3.0.0" has incorrect peer dependency "@angular/material@~9.1.3".
warning " > ngx-mat-datetime-picker@3.0.0" has incorrect peer dependency "@angular/cdk@~9.1.3".
warning " > ngx-mat-datetime-picker@3.0.0" has incorrect peer dependency "rxjs@~6.3.3".
warning " > ngx-mat-moment-adapter@1.0.0-beta.1" has incorrect peer dependency "@angular/material@0.0.0-PLACEHOLDER".
warning " > ngx-mat-moment-adapter@1.0.0-beta.1" has incorrect peer dependency "@angular/core@0.0.0-NG".
warning " > ngx-mat-moment-adapter@1.0.0-beta.1" has incorrect peer dependency "tslib@0.0.0-TSLIB".

**Comment by h2qutc** [comment]
Hi, 
This repo is no longer supported, please consider using the repository [angular-material-components](https://github.com/h2qutc/angular-material-components) instead.
This issue was fixed in [@angular-material-components/datetime-picker](@angular-material-components/datetime-picker) v2.0.1

```
npm install --save  @angular-material-components/datetime-picker
```
Free free to open issue [here](https://github.com/h2qutc/angular-material-components/issues).
Thank you very much.
