### ISSUE TITLE
Requesting support for Angular 10.x and Angular 11.x

### ISSUE THREAD

**Issue by Leccho** [h2qutc/ngx-mat-datetime-picker#63]
Would be nice to support all version of Angular!

**Comment by PetroSuch** [comment]
Does anybody have any progress in this issue ?

**Comment by h2qutc** [comment]
@PetroSuch  
this repo is no longer supported, please consider using the repository [angular-material-components/datetime-picker](https://github.com/h2qutc/angular-material-components) instead.
