### ISSUE TITLE
angular 8 bug ?

### ISSUE THREAD

**Issue by Lars-Erik75** [h2qutc/ngx-mat-datetime-picker#7]
When date is not set initially, and you try to open ngx-mat-datetime-picker it breaks with this error.

[Error] ERROR
TypeError: null is not an object (evaluating 'date.clone')
clone — material-moment-adapter.js:166
open — ngx-mat-datetime-picker.js:524
_open — datepicker.js:2889
(anonymous function)
callWithDebugContext — core.js:45631
dispatchEvent — core.js:29803
(anonymous function) — platform-browser.js:2668
onInvokeTask — core.js:39679
runTask — zone-evergreen.js:168
invokeTask — zone-evergreen.js:465
invokeTask — zone-evergreen.js:1603
globalZoneAwareCallback — zone-evergreen.js:1629
	error
	View_MatDatepickerToggle_0 (MatDatepickerToggle.ngfactory.js:14)
	logError (vendor.js:105041)
	logError
	handleError (vendor.js:69691)
	dispatchEvent (vendor.js:90579)
	(anonymous function) (vendor.js:159448)
	onInvokeTask (vendor.js:99491)
	runTask (polyfills.js:3174)
	invokeTask (polyfills.js:3471)
	invokeTask (polyfills.js:4609)
	globalZoneAwareCallback (polyfills.js:4635)

**Comment by h2qutc** [comment]
Hi, thanks for your comment, this bug is fixed in version v1.0.1.
