### ISSUE TITLE
 Null value?

### ISSUE THREAD

**Issue by carlospalacin** [h2qutc/ngx-mat-datetime-picker#9]
How can I set initial value like a null or ''? I get this error:

![Captura de pantalla 2020-01-15 a las 13 10 38](https://user-images.githubusercontent.com/7494076/72432945-90ac7780-3798-11ea-9555-159482f8820b.png)

Always I have to create a new Date to init component, for form with no required formControl will be necessary, what do you think?

Thanks!

**Comment by h2qutc** [comment]
Hi, thanks for your comment, this bug is fixed in version v1.0.1.

**Comment by carlospalacin** [comment]
Hi! 
with MatMomentDate Adapter doesn't work.

![Captura de pantalla 2020-01-17 a las 13 06 35](https://user-images.githubusercontent.com/7494076/72611382-3e9b5b80-392a-11ea-93ab-148e81ca44f2.png)

[https://stackblitz.com/edit/demo-ngx-mat-datetime-picker-tpmdxb](url)

by the way, great job!

**Comment by h2qutc** [comment]
Hi, I think that this error is fixed in version v1.0.2. Can you check it again plz?

**Comment by carlospalacin** [comment]
works fine!! thanks!!
